import { ethers } from "hardhat";
import fs from "fs";
import path from "path";
import { ImplantLot721 } from "../typechain-types";

async function main() {
    const [deployer] = await ethers.getSigners();
    console.log("🚀 Deploying contract with account:", deployer.address);

    const contract = await ethers.deployContract("ImplantLot721", [deployer.address]) as ImplantLot721;
    await contract.waitForDeployment();

    const address = await contract.getAddress();
    console.log("✅ Contract deployed to:", address);

    // Pfade vorbereiten
    const constantsPath = path.resolve(__dirname, "../../client/src/utils/constants.js");
    const artifactPath = path.resolve(__dirname, "../artifacts/contracts/ImplantLot721.sol/ImplantLot721.json");

    // ABI laden
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
    const abi = artifact.abi;

    // Inhalt für constants.js vorbereiten
    const content = `
    // 🚀 Auto-generated by deploy.ts
    export const CONTRACT_ADDRESS = "${address}";
    export const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)};
    `;

    // Schreiben
    fs.writeFileSync(constantsPath, content.trim() + "\n");
    console.log("📝 ABI & Adresse geschrieben nach client/src/utils/constants.js");
}

main().catch((error) => {
    console.error("❌ Deployment failed:", error);
    process.exitCode = 1;
});
